# Generated by Django 4.2 on 2023-11-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
